### ISSUE TITLE
Error in EasyCanvas.munki prevents repo-update

### ISSUE THREAD

**Issue by grahampugh** [autopkg/blackthroat-recipes#21]
I don't use this recipe, but doing an `autopkg repo-update blackthroat-recipes` results in the following error:

```
WARNING: plist error for /Users/serveradmin/Library/AutoPkg/RecipeRepos/com.github.autopkg.blackthroat-recipes/DEVGURU Co., Ltd./EasyCanvas.munki.recipe: unexpected key at line 32
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 2716, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 2712, in main
    return subcommands[verb]["function"](argv)
  File "/usr/local/bin/autopkg", line 811, in repo_update
    calculate_recipe_map()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 523, in calculate_recipe_map
    write_recipe_map_to_disk()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 562, in write_recipe_map_to_disk
    sort_keys=True,
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/Library/AutoPkg/Python3/Python.framework/Versions/Current/lib/python3.7/json/encoder.py", line 353, in _iterencode_dict
    items = sorted(dct.items(), key=lambda kv: kv[0])
TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

Hard to figure out what the error is from this output, but looks like there's a missing value in some JSON somewhere that's tripping it over (why that comes from a repo-update is a mystery to me).

**Comment by grahampugh** [comment]
Ah, actually it's obvious: missing key value at line 32.

**Comment by blackthroat** [comment]
Thanks for the heads up. Should be fixed with https://github.com/autopkg/blackthroat-recipes/commit/553de847ae0637b40824192de99c4cd09e8c42ae
